### ISSUE TITLE
Help Needed - Custom realm

### ISSUE THREAD

**Issue by vshank77** [elastic/shield-custom-realm-example#32]
I have been trying to write a custom extension for integrating with Spring-Security and Okta Oauth2. Followed the example and built a zip file - which has both the x-pack-extension-descriptor.properties in the JAR as well as the root of the zip file.

However when I try to install the extension, this error is thrown. Can you please help.

```
bin/x-pack/extension install file:///tmp/es-okta-realm-6.2.1.zip 
xpack extensions directory [/usr/share/elasticsearch/plugins/x-pack/x-pack-security/extensions] does not exist. Creating...
-> Downloading file:///tmp/es-okta-realm-6.2.1.zip
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/x-pack/x-pack-security/extensions/.installing-6714113117323179146/x-pack-extension-descriptor.properties
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at org.elasticsearch.xpack.core.extensions.XPackExtensionInfo.readFromProperties(XPackExtensionInfo.java:59)
	at org.elasticsearch.xpack.core.extensions.InstallXPackExtensionCommand.verify(InstallXPackExtensionCommand.java:165)
	at org.elasticsearch.xpack.core.extensions.InstallXPackExtensionCommand.install(InstallXPackExtensionCommand.java:206)
	at org.elasticsearch.xpack.core.extensions.InstallXPackExtensionCommand.execute(InstallXPackExtensionCommand.java:115)
	at org.elasticsearch.xpack.core.extensions.InstallXPackExtensionCommand.execute(InstallXPackExtensionCommand.java:102)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:75)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.xpack.core.extensions.XPackExtensionCli.main(XPackExtensionCli.java:37)
```

The contents of the x-pack-extension-descriptor.properties 

```
description=Okta Realm Extension
version=6.2.1
name=esokta
classname=io.polyglotted.esokta.OktaRealmExtension
java.version=1.8
xpack.version=6.2.1
```

**Comment by schendtj** [comment]
I'm not sure if you're still seeing this error, but in case you are...

Check to see how you're creating the .zip file. Using `tar` will cause this error, but using `zip` seems to work much better.
